apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-angular-deployment
  labels:
    app: ecom-angular-deployment
spec:
  selector: 
    matchLabels:
      app: ecom-angular-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: ecom-angular-pod
      name: ecom-angular-pod
    spec:
      containers:
      - image: rohithkakarla/ecomangular:latest
        name: ecom-ang-cont
        ports:
          - containerPort: 80
            name: ecom-ang-cont