apiVersion: v1
kind: Service
metadata:
  name: ecom-spring-service
spec:
  type: NodePort
  selector:
    app: ecom-spring-pod
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30008