apiVersion: v1
kind: PersistentVolume
metadata:
  name: ecom-mongo-pv
  labels:
    app: ecom-mongo-pv
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/db