spring:
  data:
    mongodb:
      host: '${MONGO_HOST:localhost}'
      database: '${MONGO_DB:ecom_db}'
      port: 27017
      username: '${MONGO_USERNAME:root}'
      password: '${MONGO_PASSWORD:password}'
      authentication-database: admin
       